[package]
name = "rustc-hash"
version = "1.2.0"
authors = ["The Rust Project Developers"]
description = "A speedy, non-cryptographic hashing algorithm used by rustc and Firefox"
license = "Apache-2.0/MIT"
readme = "README.md"
keywords = ["hash", "hasher", "fxhash", "rustc"]
repository = "https://github.com/rust-lang/rustc-hash"
edition = "2021"

[features]
default = ["std"]
std = []
rand = ["dep:rand", "std"]

[dependencies]
hashbrown = "0.15.0"
rand = { version = "0.8", optional = true }
